// Manjjari Holidays - Site Configuration
export const siteConfig = {
  name: "Manjjari Holidays",
  tagline: "Tour & Travel Management Company",
  description:
    "Manjjari Holidays offers premium tour planning and management services in Odisha, Chhattisgarh & India. Eco tours, tribal tours, photography tours, cab services & hotel booking.",
  phone: "+91 99387 30115",
  phoneRaw: "+919938730115",
  landline: "0674-4519290",
  landlineRaw: "06744519290",
  email: "booknow@manjjariholidays.com",
  emailDomestic: "director@manjjariholidays.com",
  bookingEmail: "booknow@manjjariholidays.com",
  whatsappNumber: "+91 8249327115",
  whatsappRaw: "918249327115",
  tokenPercentage: 20, // 20% of total as token/advance amount
  address: {
    line1: "Plot no -1962, Gothapatna",
    line2: "Near TGS Gurukul, Malipada",
    line3: "Bhubaneswar, Odisha - 751003",
    city: "Bhubaneswar",
    state: "Odisha",
    pin: "751003",
    country: "India",
    full: "Plot no -1962, Gothapatna, Near TGS Gurukul, Malipada, Bhubaneswar, Odisha - 751003",
  },
  social: {
    facebook: "https://facebook.com/manjjariholidays",
    twitter: "https://twitter.com/manjjariholidays",
    instagram: "https://instagram.com/manjjariholidays",
    youtube: "https://youtube.com/@manjjariholidays",
  },
  mapEmbed:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3742.098!2d85.824!3d20.296!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a190900040687a9%3A0x7a1e4f7b4f52e62d!2sManjjari%20Holidays!5e0!3m2!1sen!2sin!4v1700000000000",
};

export const packages = [
  {
    id: "golden-triangle-odisha",
    name: "Golden Triangle Tour Odisha",
    category: "best-offers",
    duration: "5 Days / 4 Nights",
    price: 12999,
    originalPrice: 16999,
    image: "https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/9841f211-e10d-4120-8bc2-8dbe636e607b-tropicalvacations-in/assets/images/tr1-8.jpg",
    description: "Explore the iconic golden triangle of Odisha covering Bhubaneswar, Puri & Konark. Visit ancient temples, pristine beaches and the magnificent Sun Temple.",
    highlights: ["Bhubaneswar Temples", "Puri Jagannath Temple", "Konark Sun Temple", "Chilika Lake"],
    includes: ["Hotel Accommodation", "AC Transport", "Breakfast & Dinner", "Sightseeing", "Guide"],
  },
  {
    id: "exotic-odisha",
    name: "Exotic Odisha Trip",
    category: "best-offers",
    duration: "7 Days / 6 Nights",
    price: 18999,
    originalPrice: 24999,
    image: "https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/9841f211-e10d-4120-8bc2-8dbe636e607b-tropicalvacations-in/assets/images/3-30-10.jpg",
    description: "A comprehensive tour covering the best of Odisha - from ancient temples to tribal villages, wildlife sanctuaries to serene beaches.",
    highlights: ["Tribal Villages", "Simlipal National Park", "Bhitarkanika", "Puri Beach"],
    includes: ["Hotel Accommodation", "AC Transport", "All Meals", "Sightseeing", "Expert Guide"],
  },
  {
    id: "eco-wildlife-odisha",
    name: "Eco Wildlife Tours Odisha",
    category: "eco-wildlife",
    duration: "6 Days / 5 Nights",
    price: 15999,
    originalPrice: 21999,
    image: "https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/9841f211-e10d-4120-8bc2-8dbe636e607b-tropicalvacations-in/assets/images/tr2-9.jpg",
    description: "Experience the rich biodiversity of Odisha with visits to wildlife sanctuaries, eco retreats and nature trails.",
    highlights: ["Simlipal Tiger Reserve", "Mangalajodi Bird Sanctuary", "Bhitarkanika Mangroves", "Satkosia Gorge"],
    includes: ["Eco Resort Stay", "Jeep Safari", "All Meals", "Nature Guide", "Binoculars"],
  },
  {
    id: "tribal-odisha",
    name: "Tribal Odisha Tours",
    category: "special-interest",
    duration: "8 Days / 7 Nights",
    price: 22999,
    originalPrice: 29999,
    image: "https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/9841f211-e10d-4120-8bc2-8dbe636e607b-tropicalvacations-in/assets/images/tr5-17.jpg",
    description: "Immerse yourself in the rich tribal culture of Odisha. Visit remote tribal villages of Dongria Kondh, Bonda, and Gadaba tribes.",
    highlights: ["Dongria Kondh Village", "Bonda Tribal Market", "Gadaba Dance", "Koraput Highlands"],
    includes: ["Hotel & Homestay", "4x4 Vehicle", "All Meals", "Tribal Guide", "Permits"],
  },
  {
    id: "buddhist-odisha",
    name: "Buddhist Tours Odisha",
    category: "culture-heritage",
    duration: "5 Days / 4 Nights",
    price: 11999,
    originalPrice: 15999,
    image: "https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/9841f211-e10d-4120-8bc2-8dbe636e607b-tropicalvacations-in/assets/images/tn_IMG_0880-13.jpg",
    description: "Discover the Buddhist heritage of Odisha including ancient monasteries, stupas and rock-cut caves dating back to 3rd century BC.",
    highlights: ["Ratnagiri Monastery", "Udayagiri Caves", "Lalitgiri Stupa", "Dhauli Peace Pagoda"],
    includes: ["Hotel Accommodation", "AC Transport", "Breakfast", "Guide", "Entry Fees"],
  },
  {
    id: "festival-odisha",
    name: "Festival Tours Odisha",
    category: "special-interest",
    duration: "4 Days / 3 Nights",
    price: 9999,
    originalPrice: 13999,
    image: "https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/9841f211-e10d-4120-8bc2-8dbe636e607b-tropicalvacations-in/assets/images/puri-rath-yatra-14.jpg",
    description: "Experience the vibrant festivals of Odisha including the world-famous Rath Yatra, Durga Puja, and tribal festivals.",
    highlights: ["Rath Yatra Puri", "Durga Puja", "Tribal Festivals", "Konark Dance Festival"],
    includes: ["Hotel Accommodation", "AC Transport", "Breakfast & Dinner", "VIP Access", "Guide"],
  },
  {
    id: "textile-odisha",
    name: "Textile Tours Odisha",
    category: "special-interest",
    duration: "5 Days / 4 Nights",
    price: 13999,
    originalPrice: 17999,
    image: "https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/9841f211-e10d-4120-8bc2-8dbe636e607b-tropicalvacations-in/assets/images/textile-tour-15.jpg",
    description: "Explore the rich textile heritage of Odisha - from Sambalpuri Ikat to Pattachitra paintings and Pipili applique work.",
    highlights: ["Sambalpuri Ikat Weaving", "Pattachitra Art Village", "Pipili Applique", "Silver Filigree Cuttack"],
    includes: ["Hotel Accommodation", "AC Transport", "Breakfast", "Artisan Visits", "Guide"],
  },
  {
    id: "photography-chhattisgarh",
    name: "Photography Tour Chhattisgarh",
    category: "chhattisgarh",
    duration: "7 Days / 6 Nights",
    price: 19999,
    originalPrice: 25999,
    image: "https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/9841f211-e10d-4120-8bc2-8dbe636e607b-tropicalvacations-in/assets/images/tiger-sister-16.jpg",
    description: "A photography-focused tour through Chhattisgarh's diverse landscapes, tribal communities, and wildlife areas.",
    highlights: ["Chitrakote Falls", "Bastar Tribal Markets", "Kanger Valley", "Tirathgarh Falls"],
    includes: ["Hotel Accommodation", "4x4 Vehicle", "All Meals", "Photography Guide", "Permits"],
  },
  {
    id: "chhattisgarh-tribal",
    name: "Chhattisgarh Tribal Tour",
    category: "chhattisgarh",
    duration: "6 Days / 5 Nights",
    price: 17999,
    originalPrice: 22999,
    image: "https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/9841f211-e10d-4120-8bc2-8dbe636e607b-tropicalvacations-in/assets/images/tn_20180513_142033-18.jpg",
    description: "Explore the tribal heartland of Chhattisgarh with visits to remote tribal villages, weekly markets, and cultural performances.",
    highlights: ["Bastar Dussehra", "Maria Tribe Village", "Muria Dance", "Chitrakote Waterfalls"],
    includes: ["Hotel & Homestay", "4x4 Vehicle", "All Meals", "Tribal Guide", "Permits"],
  },
  {
    id: "northeast-india",
    name: "Northeast India Trips",
    category: "india",
    duration: "10 Days / 9 Nights",
    price: 32999,
    originalPrice: 42999,
    image: "https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/9841f211-e10d-4120-8bc2-8dbe636e607b-tropicalvacations-in/assets/images/tr8-20.jpg",
    description: "Discover the unexplored beauty of Northeast India - from misty mountains to living root bridges and vibrant tribal cultures.",
    highlights: ["Meghalaya Root Bridges", "Kaziranga National Park", "Tawang Monastery", "Majuli Island"],
    includes: ["Hotel Accommodation", "AC Vehicle", "All Meals", "Expert Guide", "Inner Line Permits"],
  },
  {
    id: "south-india",
    name: "South India Tours",
    category: "india",
    duration: "8 Days / 7 Nights",
    price: 24999,
    originalPrice: 31999,
    image: "https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/9841f211-e10d-4120-8bc2-8dbe636e607b-tropicalvacations-in/assets/images/tr6-21.jpg",
    description: "Experience the diverse beauty of South India - from Kerala backwaters to Tamil Nadu temples and Karnataka coffee plantations.",
    highlights: ["Kerala Backwaters", "Meenakshi Temple", "Coorg Coffee Estates", "Hampi Ruins"],
    includes: ["Hotel Accommodation", "AC Transport", "Breakfast & Dinner", "Guide", "Houseboat Stay"],
  },
  {
    id: "mesmerizing-odisha",
    name: "Mesmerizing Odisha",
    category: "best-offers",
    duration: "6 Days / 5 Nights",
    price: 14999,
    originalPrice: 19999,
    image: "https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/9841f211-e10d-4120-8bc2-8dbe636e607b-tropicalvacations-in/assets/images/Avalokiteswar-12.jpg",
    description: "A mesmerizing journey through the cultural and natural wonders of Odisha covering temples, lakes, waterfalls and more.",
    highlights: ["Lingaraj Temple", "Chilika Lake", "Daringbadi Hill Station", "Gopalpur Beach"],
    includes: ["Hotel Accommodation", "AC Transport", "Breakfast & Dinner", "Sightseeing", "Guide"],
  },
];

export const services = [
  {
    id: "cab-services",
    name: "Cab Services",
    icon: "car",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600&h=400&fit=crop&q=80",
    description: "Our own fleet of well-maintained vehicles with experienced chauffeurs for comfortable travel across Odisha and beyond.",
    features: ["AC & Non-AC Vehicles", "GPS Tracked", "24/7 Availability", "Professional Drivers", "Sedan, SUV, Tempo Traveller"],
  },
  {
    id: "hotel-booking",
    name: "Hotel Booking",
    icon: "hotel",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&h=400&fit=crop&q=80",
    description: "Premium hotel and homestay arrangements across all destinations with best price guarantee.",
    features: ["Budget to Luxury", "Heritage Properties", "Eco Resorts", "Royal Palaces", "Home Stays"],
  },
  {
    id: "tour-planning",
    name: "Tour Planning",
    icon: "map",
    image: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=600&h=400&fit=crop&q=80",
    description: "Customized tour packages tailored to your interests, budget, and schedule by our expert travel planners.",
    features: ["Custom Itineraries", "Group Tours", "Solo Travel", "Honeymoon Packages", "Corporate Tours"],
  },
  {
    id: "guide-services",
    name: "Guide Services",
    icon: "users",
    image: "https://images.unsplash.com/photo-1527631746610-bca00a040d60?w=600&h=400&fit=crop&q=80",
    description: "Professional multilingual guides with deep knowledge of local culture, history and traditions.",
    features: ["Multilingual Guides", "Certified Professionals", "Cultural Experts", "Wildlife Specialists", "Photography Guides"],
  },
];

export const tourCategories = [
  { id: "best-offers", name: "Best Offers Odisha Tours" },
  { id: "eco-wildlife", name: "Eco Wildlife Tours Odisha" },
  { id: "special-interest", name: "Special Interest Tours Odisha" },
  { id: "culture-heritage", name: "Culture-Temples-Pilgrim-Heritage" },
  { id: "chhattisgarh", name: "Odisha & Chhattisgarh Tours" },
  { id: "india", name: "India Tours" },
];
